stackname: covidgeneric
env_folder: env_vars
replicas:
  dev: 1
  qa: 1
  uat: 1
  prod: 3
restart_policy: any
max_mem: 1024M
max_cpu: 1
traefik_application_port: 3010
traefik_https_enable: true
traefik_ssl_provider: letsencrypt
vault:
  enabled: true
  name: civicsense_students_be
  dev:
    - SECRET
    - REGION
    - APPLICATION_ARN
    - POSITIVE_TRACKER_CAMP_ID
    - COOKIE_NAME
    - REDIS_HOST
    - OTP_URL
    - OTP_TEMPLATE_ID
    - ASSET_BUCKET_NAME
    - TASK_BUCKET_NAME
    - MONGO_CONNECTION
    - SECRETACCESSKEY
    - ACCESS_KEY
    - OTP_AUTHKEY
    - KMLID
    - PHONE_NO
    - NODE_ENV
    - HEALTH_KMLID
    - TEST_KMLID
    - COVID_TRACKER
    - AWS_IAM_ACCOUNT_ID
    - AWS_IAM_ROLE_SESSION_NAME
    - AWS_IAM_ROLE_ARN
    - AWS_IAM_POOL_ID
    - AWS_IAM_REGION
    - AWS_QS_REGION
    - AWS_QS_DASHBOARD_ID


  prod:
    - SECRET
    - REGION
    - APPLICATION_ARN
    - POSITIVE_TRACKER_CAMP_ID
    - COOKIE_NAME
    - REDIS_HOST
    - OTP_URL
    - OTP_TEMPLATE_ID
    - ASSET_BUCKET_NAME
    - TASK_BUCKET_NAME
    - MONGO_CONNECTION
    - SECRETACCESSKEY
    - ACCESS_KEY
    - OTP_AUTHKEY
    - KMLID
    - PHONE_NO
    - NODE_ENV
    - HEALTH_KMLID
    - TEST_KMLID
    - COVID_TRACKER
    - AWS_IAM_ACCOUNT_ID
    - AWS_IAM_ROLE_SESSION_NAME
    - AWS_IAM_ROLE_ARN
    - AWS_IAM_POOL_ID
    - AWS_IAM_REGION
    - AWS_QS_REGION
    - AWS_QS_DASHBOARD_ID
